function generate_menu
    global handles values;
    set( handles.fig_main,'Menubar','none');
    handles.me_handle(1)=uimenu     ( handles.fig_main, 'Label','&Game');
    handles.me_handle(2)=uimenu     ( handles.fig_main, 'Label','&Help');
    handles.sub_menu(1)=uimenu (handles.me_handle(1),'Label','New',...
                                            'Callback',[values.MD ' NewGame']);
    handles.sub_menu(2)=uimenu (handles.me_handle(1),'Label','Beginner',...
                                            'Callback',[values.MD ' Beginner']);
    handles.sub_menu(3)=uimenu (handles.me_handle(1),'Label','Intermediate',...
                                            'Callback',[values.MD ' Intermediate']);
    handles.sub_menu(4)=uimenu (handles.me_handle(1),'Label','Expert',...
                                           'Callback',[values.MD ' Expert']); 
    handles.sub_menu(5)=uimenu (handles.me_handle(1),'Label','user_define',...
                                           'Callback',[values.MD ' user_define']);                                    
    handles.sub_menu(6)=uimenu (handles.me_handle(1),'Label','Exit',...
                                           'Callback',[values.MD ' Exit']);
    handles.me_handle(7)=uimenu     ( handles.me_handle(2), 'Label','Help',...
                                            'Callback',[values.MD ' Help']);                               
    values.timer='0.0';                                   
    handles.timer = uicontrol(handles.fig_main,...
                                        'Style','edit',...
                                        'Unit','normalized',...
                                        'Backgroundcolor','[.90 .90 .90]',...
                                        'Position',[0.9 0.9 0.1 0.1],...
                                        'String',values.timer,...
                                        'Enable','inactive',...
                                        'FontWeight','bold',...
                                        'FontSize',14);
    handles.Mines = uicontrol(handles.fig_main,...
                                        'Style','edit',...
                                        'Unit','normalized',...
                                        'Backgroundcolor','[.90 .90 .90]',...
                                        'Position',[0.1 0.9 0.1 0.1],...
                                        'String',values.mines,...
                                        'Enable','inactive',...
                                        'FontWeight','bold',...
                                        'FontSize',14);                                         
end
