function generate_menu
    global handles values;
    handles.menu_1=uimenu( handles.fig_main,...
        'Label','&Game');
    handles.menu_1_1=uimenu(handles.menu_1,...
        'Label','&New',...
        'Callback',[values.MD ' NewGame'],...
        'Accelerator','n');
    handles.menu_1_2=uimenu(handles.menu_1,...
        'Label','&Difficulty');
    handles.menu_1_2_1=uimenu(handles.menu_1_2,...
        'Label','&Beginner',...
        'Callback',[values.MD ' Values_Beginner'],...
        'Accelerator','1');
    handles.menu_1_2_2=uimenu(handles.menu_1_2,...
        'Label','&Intermediate',...
        'Callback',[values.MD ' Values_Intermediate'],...
        'Accelerator','2');
    handles.menu_1_2_3=uimenu(handles.menu_1_2,...
        'Label','&Expert',...
        'Callback',[values.MD ' Values_Expert'],...
        'Accelerator','3'); 
    handles.menu_1_2_4=uimenu(handles.menu_1_2,...
        'Label','&Custom',...
        'Callback',[values.MD ' Values_Custom'],...
        'Accelerator','4',...
        'Separator','on');
  %  handles.menu_1_3=uimenu(handles.menu_1,...
  %      'Label','&Highscore',...
  %      'Callback',[values.MD ' Highscore'],...
  %      'Accelerator','c',...
  %      'Separator','on');
  %  handles.menu_1_3=uimenu(handles.menu_1,...
  %      'Label','&Statistics',...
  %      'Callback',[values.MD ' Statistics'],...
  %      'Accelerator','s');
    handles.menu_1_5=uimenu(handles.menu_1,...
        'Label','E&xit',...
        'Callback',[values.MD ' Exit'],...
        'Accelerator','x',...
        'Separator','on');
    handles.menu_2=uimenu( handles.fig_main,...
        'Label','&Help');
    handles.menu_2_1=uimenu(handles.menu_2,...
        'Label','View &Help',...
        'Accelerator','h',...
        'Callback',[values.MD ' Help']);
    handles.menu_2_2=uimenu(handles.menu_2,...
        'Label','&About MineDetector',...
        'Accelerator','a',...
        'Callback',[values.MD ' About']);                                         
end
