function generate_buttons()
%GENERATE_BUTTONS Summary of this function goes here
%   Detailed explanation goes here

    global handles values;
    
    if values.customizing
        values.field_size = [0.9/values.width 0.8/values.height];
    else
        values.field_size = [0.9/values.width 0.8/values.height];
    end
    
    for i=1:1:values.height
        for j=1:1:values.width
            field_x = num2str(i);
            field_y = num2str(j);
            cb_rightclick = strcat(' rc|', field_x, '|', field_y);
            cb_leftclick  = strcat(' lc|', field_x, '|', field_y);
            handles.field(i,j) = uicontrol(handles.fig_main,...
                'Style','push',...
                'Unit','normalized',...
                'Position',[1/values.width*(j-1) 0.95/values.height*(i-1) values.field_size],...
                'ButtonDownFcn',[values.MD cb_rightclick],...
                'Callback',[values.MD cb_leftclick]);
            if values.customizing
                set(handles.field(i,j),'Position',[0.95/values.width*(j-1) 0.05+0.9/values.height*(i-1) values.field_size]);
            end
        end
    end %Feld-Aufbau mit verschiedenen Callbacks
    
    if values.customizing
        handles.custom_close = uicontrol(handles.fig_main,...
            'Style','push',...
            'Unit','normalized',...
            'Position',[0.95 0 0.05 0.05],...
            'String','OK',...
            'FontWeight','bold',...
            'FontSize',12,...
            'Callback',[values.MD ' custom|close']);        
        handles.custom_width_minus = uicontrol(handles.fig_main,...
            'Style','push',...
            'Unit','normalized',...
            'Position',[0.95 0.425 0.05 0.05],...
            'String','-',...
            'FontWeight','bold',...
            'FontSize',12,...
            'Callback',[values.MD ' custom|width|minus']);
        handles.custom_width_value = uicontrol(handles.fig_main,...
            'Style','edit',...
            'Unit','normalized',...
            'Position',[0.95 0.475 0.05 0.05],...
            'String',values.width,...
            'FontWeight','bold',...
            'Enable','inactive',...
            'FontSize',12);
        handles.custom_width_plus = uicontrol(handles.fig_main,...
            'Style','push',...
            'Unit','normalized',...
            'Position',[0.95 0.525 0.05 0.05],...
            'String','+',...
            'FontWeight','bold',...
            'FontSize',12,...
            'Callback',[values.MD ' custom|width|plus']);
        handles.custom_height_minus = uicontrol(handles.fig_main,...
            'Style','push',...
            'Unit','normalized',...
            'Position',[0.425 0 0.05 0.05],...
            'String','-',...
            'FontWeight','bold',...
            'FontSize',12,...
            'Callback',[values.MD ' custom|height|minus']);
        handles.custom_height_value = uicontrol(handles.fig_main,...
            'Style','edit',...
            'Unit','normalized',...
            'Position',[0.475 0 0.05 0.05],...
            'String',values.height,...
            'FontWeight','bold',...
            'Enable','inactive',...
            'FontSize',12);
        handles.custom_height_plus = uicontrol(handles.fig_main,...
            'Style','push',...
            'Unit','normalized',...
            'Position',[0.525 0 0.05 0.05],...
            'String','+',...
            'FontWeight','bold',...
            'FontSize',12,...
            'Callback',[values.MD ' custom|height|plus']);
        handles.custom_mines_minus = uicontrol(handles.fig_main,...
            'Style','push',...
            'Unit','normalized',...
            'Position',[0.11 0.95 0.05 0.025],...
            'String','-',...
            'FontWeight','bold',...
            'FontSize',12,...
            'Callback',[values.MD ' custom|mines|minus']);
        handles.custom_mines_plus = uicontrol(handles.fig_main,...
            'Style','push',...
            'Unit','normalized',...
            'Position',[0.11 0.975 0.05 0.025],...
            'String','+',...
            'FontWeight','bold',...
            'FontSize',12,...
            'Callback',[values.MD ' custom|mines|plus']);
    end
    
    set(handles.field(1,1),'Unit','pixels');
    values.img_size = handles.field(1,1).Position(1,3:4) * 0.5;
    set(handles.field(1,1),'Unit','normalized');
end

