function user_define( varargin )

global handles values;
cb=mfilename;
if nargin == 0
    values.User = 1;
    %Initialisierung
    handles.fig_user = figure(...
        'NumberTitle','off',...
        'Name','User_define');
    set( handles.fig_user,'Menubar','none');
    handles.pb_handle=uicontrol   (handles.fig_user,'Style','push',...
                                            'Unit','normalized',...
                                            'position',[0.75 0.05 0.2 0.1],...
                                            'String','Ready',...
                                            'Callback',[cb ' Exit']);
    handles.sl1_handle=uicontrol  (handles.fig_user,'Style','slider',...
                                            'Unit','normalized',...
                                            'position',[0.1 0.8 0.3 0.1],...
                                            'Min',5,'max',30,'value',9,...
                                            'Callback',[cb ' sl1_handle']);
    handles.sl2_handle=uicontrol  (handles.fig_user,'Style','slider',...
                                            'Unit','normalized',...
                                            'position',[0.6 0.8 0.3 0.1],...
                                            'Min',5,'max',30,'value',9,...
                                            'Callback',[cb ' sl2_handle']);       
    handles.sl3_handle=uicontrol  (handles.fig_user,'Style','slider',...
                                            'Unit','normalized',...
                                            'position',[0.2 0.4 0.6 0.2],...
                                            'Min',5,'max',120,'value',10,...
                                            'Callback',[cb ' sl3_handle']);
    handles.sl1min_txt=uicontrol  (handles.fig_user,'Style','text',...
                                            'Unit','normalized',...
                                            'position',[0.1 0.9 0.04 0.04],...
                                            'String',num2str(get( handles.sl1_handle,'min')));       
    handles.sl1max_txt=uicontrol  (handles.fig_user,'Style','text',...
                                            'Unit','normalized',...
                                            'position',[0.36 0.9 0.04 0.04],...
                                            'String',num2str(get( handles.sl1_handle,'max')));          
    handles.sl2min_txt=uicontrol (handles.fig_user,'Style','text',...
                                            'Unit','normalized',...
                                            'position',[0.6 0.9 0.04 0.04],...
                                            'String',num2str(get( handles.sl2_handle,'min')));       
    handles.sl2max_txt=uicontrol  (handles.fig_user,'Style','text',...
                                            'Unit','normalized',...
                                            'position',[0.86 0.9 0.04 0.04],...
                                            'String',num2str(get( handles.sl2_handle,'max')));                    
    handles.sl3min_txt=uicontrol  (handles.fig_user,'Style','text',...
                                            'Unit','normalized',...
                                            'position',[0.2 0.6 0.04 0.04],...
                                            'String',num2str(get( handles.sl3_handle,'min')));       
    handles.sl3max_txt=uicontrol  (handles.fig_user,'Style','text',...
                                            'Unit','normalized',...
                                            'position',[0.75 0.6 0.04 0.04],...
                                            'String',num2str(get( handles.sl3_handle,'max')));                                      
    handles.width.valure_txt=uicontrol(handles.fig_user,'Style','text',...
                                            'Unit','normalized',...
                                            'position',[0.225 0.9 0.04 0.04],...
                                            'String',num2str(values.width)); 
    handles.height.valure_txt=uicontrol(handles.fig_user,'Style','text',...
                                            'Unit','normalized',...
                                            'position',[0.74 0.9 0.04 0.04],...
                                            'String',num2str(values.height));
    handles.mines.valure_txt=uicontrol(handles.fig_user,'Style','text',...
                                            'Unit','normalized',...
                                            'position',[0.5 0.6 0.04 0.04],...
                                            'String',num2str(values.mines));
    handles.sl1.n_txt=uicontrol  (handles.fig_user,'Style','text',...
                                            'Unit','normalized',...
                                            'position',[0.15 0.7 0.2 0.04],...
                                            'String','Width');  
    handles.sl2.n_txt=uicontrol (handles.fig_user,'Style','text',...
                                            'Unit','normalized',...
                                            'position',[0.65 0.7 0.2 0.04],...
                                            'String','Height');
    handles.sl3.n_txt=uicontrol  (handles.fig_user,'Style','text',...
                                            'Unit','normalized',...
                                            'position',[0.4 0.3 0.2 0.04],...
                                            'String','Mines');
    MineDetector( 'NewGame' )                                    

else
  switch varargin{:}
        case 'Exit'
            m=round((values.height*values.width)/4);
            if m<values.mines
                values.mines=m;
            end %Sicherheitsüberprüfung für maximale Minenzahl
            values.User = 0; 
            MineDetector( 'user' )
           close(handles.fig_user); 
        case 'sl1_handle' 
            delete_field
            values.width= round(get(handles.sl1_handle,'Value'));
            set(handles.width.valure_txt,'String',num2str(values.width))
            generate_buttons
        case 'sl2_handle'
            delete_field
            values.height= round(get(handles.sl2_handle,'Value'));
            set(handles.height.valure_txt,'String',num2str(values.height))
            generate_buttons
        case 'sl3_handle' 
            values.mines= round(get(handles.sl3_handle,'Value'));
            set(handles.mines.valure_txt,'String',num2str(values.mines))
  end
end
end
