function Win ( varargin )
global handles values;
cb=mfilename;
if nargin == 0
    values.User = 1;
    %Initialisierung
    handles.fig_win = figure(...
        'NumberTitle','off');
    set( handles.fig_win,'Menubar','none');
    handles.pb_handle=uicontrol   (handles.fig_win,'Style','push',...
                                            'Unit','normalized',...
                                            'position',[0.75 0.05 0.2 0.1],...
                                            'String','Exit',...
                                            'Callback',[cb ' Exit']);
    handles.txt = uicontrol(handles.fig_win,...
                                        'Style','text',...
                                        'Unit','normalized',...
                                        'Backgroundcolor','[.90 .90 .90]',...
                                        'Position',[0.25 0.5 0.5 0.25],...
                                        'String','You Win',...
                                        'Enable','inactive',...
                                        'FontWeight','bold',...
                                        'FontSize',14);  
else                                  
  switch varargin{:}
        case 'Exit'
           close(handles.fig_win); 
  end
end
                                
end
