function Win ( varargin )
global handles values;
cb=mfilename;
if nargin == 0
    %Initialisierung
    screen = get(0,'screensize');
    handles.fig_win = figure(...
        'NumberTitle','off',...
        'Name','Congratulations!',...
        'Menubar','none',...
        'Position',[screen(1,3)/2 screen(1,4)/2 250 100]);
    handles.pb_handle=uicontrol(handles.fig_win,...
        'Style','push',...
        'Unit','normalized',...
        'Position',[0.65 0.05 0.3 0.2],...
        'String','Ok',...
        'Callback',[cb ' Exit']);
    handles.txt = uicontrol(handles.fig_win,...
        'Style','text',...
        'Unit','normalized',...
        'Position',[0.25 0.5 0.5 0.25],...
        'String','Game won!',...
        'Enable','inactive',...
        'FontWeight','bold',...
        'FontSize',14);  
else                                  
  switch varargin{:}
        case 'Exit'
           close(handles.fig_win); 
  end
end
                                
end
